postgresql:
  image: postgres:9.4.4
  environment:
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql

redmine:
  image: redevm:0.1.6
  mem_limit: 650m
  links:
    - postgresql:postgresql
  environment:
    - DB_TYPE=postgresql
    - DB_POOL=5
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_ADAPTER=postgresql
    - DB_NAME=redmine_production
    - DB_ENCODING=UTF-8
    - TZ=Asia/Kolkata
    - RAILS_ENV=production

    - REDMINE_PORT=10083
    - REDMINE_HTTPS=false
    - REDMINE_RELATIVE_URL_ROOT=
    - REDMINE_SECRET_TOKEN=

    - REDMINE_SUDO_MODE_ENABLED=false
    - REDMINE_SUDO_MODE_TIMEOUT=15

    - REDMINE_CONCURRENT_UPLOADS=2

    - REDMINE_BACKUP_SCHEDULE=
    - REDMINE_BACKUP_EXPIRY=
    - REDMINE_BACKUP_TIME=

    - SMTP_ENABLED=false
    - SMTP_METHOD=smtp
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_INTERVAL=30

  ports:
    - "80:80"
    - "9292:9292" # bundle exec thin start -R private_pub.ru -e production -a 0.0.0.0 -p 9292
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
