development:
  adapter: postgresql
  encoding: unicode
  database: redmine
  host: postgresql
  port: 5432
  username: postgres
  password: "postgres"
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: redmine
  host: postgresql
  port: 5432
  username: postgres
  password: "postgres"
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  database: redmine_test
  host: postgresql
  port: 5432
  username: postgres
  password: "postgres"
  pool: 5
