production:
  adapter: postgresql
  database: redmine_production
  host: postgresql
  username: postgres
  password: postgres
  encoding: utf8

development:
  adapter: postgresql
  database: redmine_development
  host: postgresql
  username: postgres
  password: postgres
  encoding: utf8
